src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $Nom;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $Prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;


    /**
     * @ORM\Column(type="string", length=255)
     */
    public $category;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use Composer\Util\Http\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/cart", name="cart_")
 */
class CartController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(SessionInterface $session, ArticleRepository $productsRepository): \Symfony\Component\HttpFoundation\Response
    {
        $panier = $session->get("panier", []);

        // On "fabrique" les données
        $dataPanier = [];
        $total = 0;

        foreach($panier as $id => $quantite){
            $product = $productsRepository->find($id);
            $dataPanier[] = [
                "produit" => $product,
                "quantite" => $quantite
            ];

            $total += $product->getPrix() * $quantite;
        }

        return $this->render('cart/index.html.twig',
            compact("dataPanier", "total"));
    }

    /**
     * @Route("/add/{id}", name="add")
     */
    public function add(Article $product, SessionInterface $session)
    {
        // On récupère le panier actuel
        $panier = $session->get("panier", []);
        $id = $product->getId();

        if(!empty($panier[$id])){
            $panier[$id]++;
        }else{
            $panier[$id] = 1;
        }

        // On sauvegarde dans la session
        $session->set("panier", $panier);

        return $this->redirectToRoute("cart_index");
    }

    /**
     * @Route("/remove/{id}", name="remove")
     */
    public function remove(Article $product, SessionInterface $session)
    {
        // On récupère le panier actuel
        $panier = $session->get("panier", []);
        $id = $product->getId();

        if(!empty($panier[$id])){
            if($panier[$id] > 1){
                $panier[$id]--;
            }else{
                unset($panier[$id]);
            }
        }

        // On sauvegarde dans la session
        $session->set("panier", $panier);

        return $this->redirectToRoute("cart_index");
    }

    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function delete(Article $product, SessionInterface $session)
    {
        // On récupère le panier actuel
        $panier = $session->get("panier", []);
        $id = $product->getId();

        if(!empty($panier[$id])){
            unset($panier[$id]);
        }

        // On sauvegarde dans la session
        $session->set("panier", $panier);

        return $this->redirectToRoute("cart_index");
    }

    /**
     * @Route("/delete", name="delete_all")
     */
    public function deleteAll(SessionInterface $session)
    {
        $session->remove("panier");

        return $this->redirectToRoute("cart_index");
    }

}

templates/cart/index.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Panier</title>


    {% block stylesheets %}{% endblock %}
</head>


{% block body %}
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container" >



            <div class="collapse navbar-collapse" id="mobile-nav">
                <ul class="navbar-nav">
                    <li class="nav-link active">
                        <a href="{{ "http://localhost:8000/home"}}"  class="nav-link active"> Home</a>
                    </li>


                    <li class="nav-link active">
                        <a href="{{ "http://localhost:8000/cart/"}}" class="nav-link active">Votre Panier</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-light" type="submit" >Search</button>
                </form>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mobile-nav">
                <span class="navbar-toggle-icon"></span>
            </button>

            <a class="btn btn-outline-light" href="{{ path('app_logout') }}">Log Out</a>
        </div>
    </nav>

    <section class="w-25 p-3">
        <h1>Votre panier</h1>
    </section>

    <table class="table">
        <thead>
        <tr>
            <th>Produit</th>
            <th>Prix</th>
            <th>Quantité</th>
            <th>Total</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for element in dataPanier %}
            <tr>
                <td>{{ element.produit.nom }}</td>
                <td >{{ element.produit.prix }} €</td>
                <td >{{ element.quantite }}</td>
                <td >{{ element.quantite * element.produit.prix }} €</td>
                <td>


                    <a href="{{path("cart_add", {id: element.produit.id})}}" class="btn btn-success">
                        <i class="bi bi-cart-plus"></i>
                    </a>


                    <a href="{{path("cart_remove", {id: element.produit.id})}}" class="btn btn-warning">
                        <i class="bi bi-cart-dash"></i>
                    </a>
                    <a href="{{path("cart_delete", {id: element.produit.id})}}" class="btn btn-danger">
                        <i class="bi bi-cart-x"></i>
                    </a>
                </td>
            </tr>



        {% else %}
            <tr>
                <td colspan="5" class="text-center">Votre panier est vide</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3"><b>Total</b></td>
            <td class="text-end"><b>{{ total }} €</b></td>

        </tr>
        </tfoot>
    </table>
    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-4">
                <h4>Contact Us</h4>
                <!-- Facebook -->
                <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
                ><i class="fa fa-facebook-f" style="font-size:24px"></i></a>

                <!-- Twitter -->
                <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
                ><i class="fa fa-twitter" style="font-size:24px"></i></a>

                <!-- Google -->
                <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
                ><i class="fa fa-google" style="font-size:24px"></i></a>

                <!-- Instagram -->
                <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
                ><i class="fa fa-instagram" style="font-size:24px"></i></a>

                <!-- Github -->
                <a class="btn btn-outline-light btn-floating m-1" href="#" role="button"
                ><i class="fa fa-github" style="font-size:24px"></i></a>
            </section>
            <!-- Section: Social media -->
        </div>
        <div class="row">
            <div class="col-4">
                <h3>What is E-commerce ?</h3>
                <p>
                    eCommerce is the buying and selling of goods and services online. The main root of the word “commerce” is defined as the exchange of goods and services between businesses, people, or entities.
                </p>
            </div>
            <div class="col-4">
                <h3>Services</h3>

                <p >Web design</p>
                <p>Development</p>
                <p>Hosting</p>

            </div>
            <div class="col-4">
                <h3 class="text-center">About</h3>

                <p>Company</p>
                <p>Team</p>
                <p>Careers</p>

            </div>


        </div>
        <!-- Grid container -->

        <!-- Copyright -->

        <!-- Copyright -->
    </footer>
{% endblock %}